spring:
  application.name: consumerDemo
kafka:
  bootstrapUrl: localhost:9092
  topic-name: input-topic
  consumer:
    group-name: input-topic-group
    offset-config: earliest
    offset-to-read-from: 15L

jaeger.tracer:
  host: localhost
  port: 6831